---
providers:
- name: openrouteservice
  base_url: https://api.openrouteservice.org
  key:
  limit: 40
  unit: minute
  endpoints:
    directions: "/directions"
    isochrones: "/isochrones"
    matrix: "/matrix"
    geocoding: "/geocoding"
  ENV_VARS:
    ORS_REMAINING: "X-Ratelimit-Remaining"
    ORS_QUOTA: "X-Ratelimit-Limit"